export default {
  // Auth actions
  GET_USER__START: 'GET_USER__START',
  GET_USER__SUCESS: 'GET_USER__SUCESS',
  GET_USER__ERROR: 'GET_USER__ERROR',
  LOGIN__START: 'LOGIN__START',
  LOGIN__SUCCESS: 'LOGIN__SUCCESS',
  LOGIN__ERROR: 'LOGIN__ERROR',
  LOGOUT: 'LOGOUT',

  // Run actions
  GET_ALL_RUNS__START: 'GET_ALL_RUNS__START',
  GET_ALL_RUNS__SUCCESS: 'GET_ALL_RUNS__SUCCESS',
  GET_ALL_RUNS__ERROR: 'GET_ALL_RUNS__ERROR',
  GET_RUN__START: 'GET_RUN__START',
  GET_RUN__SUCCESS: 'GET_RUN__SUCCESS',
  GET_RUN__ERROR: 'GET_RUN__ERROR',
  EDIT_RUN__START: 'EDIT_RUN__START',
  EDIT_RUN__SUCCESS: 'EDIT_RUN__SUCCESS',
  EDIT_RUN__ERROR: 'EDIT_RUN__ERROR',

  // Daily Stats actions
  GET_ALL_DAILY_STATS__START: 'GET_ALL_DAILY_STATS__START',
  GET_ALL_DAILY_STATS__SUCCESS: 'GET_ALL_DAILY_STATS__SUCCESS',
  GET_ALL_DAILY_STATS__ERROR: 'GET_ALL_DAILY_STATS__ERROR',
}
