export default {
  GET_USER__START: 'GET_USER__START',
  GET_USER__SUCESS: 'GET_USER__SUCESS',
  GET_USER__ERROR: 'GET_USER__ERROR',
  LOGIN__START: 'LOGIN__START',
  LOGIN__SUCCESS: 'LOGIN__SUCCESS',
  LOGIN__ERROR: 'LOGIN__ERROR',
  LOGOUT: 'LOGOUT',
}
